Documentation Pull Request
draeger-lab/SBSCL pull request #57
Opened 2020-08-20 06:01 UTC by hemilpanchiwala

This PR
- updates the complete documentation of SBSCL
- updates the site files of SBSCL
- adds UserGuidelines to use the features of SBSCL
- adds sequence diagrams for the developers to understand the workflow of SBSCL
- updates README.md

Many small updates have been made with the above-mentioned points in the PR.

2020-08-20 09:24 UTC, draeger requested changes

2020-08-20 09:24 UTC, draeger commented on src/main/java/org/simulator/examples/CompExample.java
> +    MultiTable solution = compSimulator.solve(timeEnd = 100.0, stepSize = 0.1);
As always, could we please use `100d` and `0.1d`?

2020-08-25 13:12 UTC, shalinshah1993 commented
- Some links are missing in dependencies.html page. For example, `libkisao`, `GLPKSolverPack`, etc.
- In summary.html, there is version 1.5. After the changes should we update at least the minor version? 
- In the current management.html page, the link points to shalinshah1993's SBSCL version. Great to see you fixed that! 

- BTW this is also a good chance to update pictures in team page, if anyone wants to add? For example, we can add @zakharc there

Otherwise ... 
![image](https://user-images.githubusercontent.com/2164796/91178319-f8259080-e6b2-11ea-91a2-9c01bb7d3a00.png)

2020-08-25 13:35 UTC, matthiaskoenig approved these changes
Some smaller wording comments. Otherwise this looks very good.

2020-08-25 13:35 UTC, matthiaskoenig commented on UserGuidelines.md
> +- You can now print the [MultiTable](https://github.com/draeger-lab/SBSCL/blob/master/src/main/java/org/simulator/math/odes/MultiTable.java) or can plot it using the [PlotMultiTable](https://github.c
```suggestion
- One can now print the [MultiTable](https://github.com/draeger-lab/SBSCL/blob/master/src/main/java/org/simulator/math/odes/MultiTable.java) or can plot it using the [PlotMultiTable](https://github.com/draeger-lab/SBSCL/blob/master/src/main/java/org/simulator/plot/PlotMultiTable.java) where you can see the changing values in a graphical form. Also, you can view it in a tabular form using the JTable class.
```

2020-08-25 13:35 UTC, matthiaskoenig commented on UserGuidelines.md
> +For complete code on how to simulate the SBML model, please refer to the [SimulatorExample](https://github.com/draeger-lab/SBSCL/blob/master/src/main/java/org/simulator/examples/SimulatorExample.java
```suggestion
For the complete code on how to simulate an SBML model, please refer to the [SimulatorExample](https://github.com/draeger-lab/SBSCL/blob/master/src/main/java/org/simulator/examples/SimulatorExample.java) in the repository.
```

2020-08-25 13:35 UTC, matthiaskoenig commented on UserGuidelines.md
> +- After creating the instance, you have to call `solve()` method of the CompSimulator class with duration and step size to get the results in the form of MultiTable.
```suggestion
- After creating the instance of the simulator, you have to call the`solve()` method of the CompSimulator class with duration and step size to get the results in the form of MultiTable.
```

2020-08-25 13:35 UTC, matthiaskoenig commented on UserGuidelines.md
> +For complete code on how to simulate the comp model, please refer to the [CompExample](https://github.com/draeger-lab/SBSCL/blob/master/src/main/java/org/simulator/examples/CompExample.java) in the r
```suggestion
For the complete code on how to simulate the comp model, please refer to the [CompExample](https://github.com/draeger-lab/SBSCL/blob/master/src/main/java/org/simulator/examples/CompExample.java) in the repository.
```

2020-08-25 13:35 UTC, matthiaskoenig commented on UserGuidelines.md
> +- Similar to the CompSimulator, here we have to provide the [SBMLDocument](https://github.com/sbmlteam/jsbml/blob/master/core/src/org/sbml/jsbml/SBMLDocument.java) by reading from the file to the [Fl
```suggestion
- Similar to the CompSimulator, here we have to provide the [SBMLDocument](https://github.com/sbmlteam/jsbml/blob/master/core/src/org/sbml/jsbml/SBMLDocument.java) by reading from the file to the [FluxBalanceAnalysis](https://github.com/draeger-lab/SBSCL/blob/master/src/main/java/org/simulator/fba/FluxBalanceAnalysis.java) class which implements all the flux balance analysis functionality.
```

2020-08-25 13:35 UTC, matthiaskoenig commented on UserGuidelines.md
> +- After this, you just need to call `solve()` method of FluxBalanceAnalysis that returns a boolean whether the results are processed successfully or not.
```suggestion
- After this, you just need to call `solve()` method of FluxBalanceAnalysis that returns a boolean indicating of the simulation was successful.
```

2020-08-25 13:35 UTC, matthiaskoenig commented on UserGuidelines.md
> +- Once `solve()` method returns true, you can access different results as described below in the snippet.
```suggestion
- After solving the FBA problem the simulation results can be accessed via.  
```

2020-08-25 13:35 UTC, matthiaskoenig commented on UserGuidelines.md
> +All the supported algorithms for stochastic simulation are present under the [/java/fern/simulation/algorithm](https://github.com/draeger-lab/SBSCL/tree/master/src/main/java/fern/simulation/algorithm
```suggestion
All supported algorithms for stochastic simulation are available in the [/java/fern/simulation/algorithm](https://github.com/draeger-lab/SBSCL/tree/master/src/main/java/fern/simulation/algorithm) directory.
```

2020-08-25 13:35 UTC, matthiaskoenig commented on UserGuidelines.md
> +**Note:** If your SBML models contain any events, then the network has to call `registerEvents()` method passing the simulator as to keep track of event properties like trigger, delays, and others by
```suggestion
**Note:** If your SBML model contains any events, then the network has to call `registerEvents()` passing the simulator as to keep track of event properties like trigger, delays, and others by the [SBMLEventHandlerObserver](https://github.com/draeger-lab/SBSCL/blob/master/src/main/java/fern/network/sbml/SBMLEventHandlerObserver.java).
```

2020-08-25 13:36 UTC, hemilpanchiwala commented
> Some links are missing in dependencies.html page. For example, libkisao, GLPKSolverPack, etc.

@shalinshah1993, the links are generated automatically by the command `mvn site`. But the links are not generated for the 4 libraries as they are used in maven from the `lib` folder only (they are present in repository only and others are from maven).

2020-08-25 13:41 UTC, matthiaskoenig commented
Please add the diagrams to the User Guidelines. I don't see the diagrams anywhere displayed. These should be part of the documentation and not only exist in a folder.

2020-08-27 12:38 UTC, merged